// Generated by CoffeeScript 1.9.3
(function() {
  var ImageItem, Item, Screen, canvas, config, ctx, downness, dt, frame, helpers, keysdown, last, now, render, screen, screens, step, update,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  config = {
    fps: 60,
    credits: "By GeckoGames",
    alphaThreshold: 210,
    keys: {
      down: 40
    },
    version: "develop",
    eggo: 20,
    mindown: 30
  };

  screens = [];

  screen = 0;

  helpers = {
    updateCanvasSize: function() {
      canvas.width = window.innerWidth || document.clientWidth || document.body.clientWidth;
      return canvas.height = window.innerHeight || document.clientHeight || document.body.clientHeight;
    },
    toCanvasTerms: function(x, y, height) {
      var originx, originy;
      originx = canvas.width / 2 - screens[screen].calcOrigin();
      originy = canvas.height / 2 - screens[screen].height / 2;
      return {
        x: originx + x,
        y: canvas.height - (originy + y) - height
      };
    },
    timestamp: function() {
      var ref;
      return (ref = window.performance.now()) != null ? ref : new Date().getTime();
    },
    getImageAlpha: function(image, x, y) {
      var cvctx;
      cvctx = document.createElement("canvas").getContext("2d");
      cvctx.drawImage(image, 0, 0);
      return cvctx.getImageData(x, y, 1, 1).data[3];
    },
    muted: false,
    toggleMute: function() {
      var i, j, len, results;
      this.muted = !this.muted;
      if (localStorage) {
        localStorage.muted = this.muted;
      }
      results = [];
      for (j = 0, len = screens.length; j < len; j++) {
        i = screens[j];
        if (i.music) {
          results.push(i.music.volume = this.muted ? 0 : 1);
        } else {
          results.push(void 0);
        }
      }
      return results;
    },
    keyStatus: function(kid) {
      return keysdown[config.keys[kid] || kid];
    }
  };

  canvas = document.querySelector('#cvas');

  ctx = canvas.getContext('2d');

  update = function() {
    var i, j, k, l, len, len1, len2, o, ref, results;
    ref = screens[screen].items;
    for (j = 0, len = ref.length; j < len; j++) {
      i = ref[j];
      i.update();
    }
    for (k = 0, len1 = keysdown.length; k < len1; k++) {
      i = keysdown[k];
      i = i !== 0 ? 1 : 0;
    }
    results = [];
    for (i = l = 0, len2 = screens.length; l < len2; i = ++l) {
      o = screens[i];
      if (o.music && i !== screen) {
        o.music.pause();
        results.push(o.music.currentTime = 0);
      } else {
        results.push(o.music.play());
      }
    }
    return results;
  };

  render = function() {
    var coords, i, j, len, ref, results;
    helpers.updateCanvasSize();
    ctx.textAlign = "center";
    ctx.fillStyle = "#fff";
    ctx.font = "10px sans-serif";
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.fillText(config.credits + " - v " + config.version, canvas.width / 2, canvas.height - 10);
    ref = screens[screen].items;
    results = [];
    for (j = 0, len = ref.length; j < len; j++) {
      i = ref[j];
      coords = helpers.toCanvasTerms(i.x, i.y, i.image.height);
      if (i.image) {
        results.push(ctx.drawImage(i.image, coords.x, coords.y));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  now = 0;

  dt = 0;

  last = helpers.timestamp();

  step = 1 / config.fps;

  frame = function() {
    now = helpers.timestamp();
    dt = dt + Math.min(1, (now - last) / 1000);
    while (dt > step) {
      dt = dt - step;
      update();
    }
    render();
    last = now;
    return requestAnimationFrame(frame);
  };

  window.onload = function() {
    if (localStorage && localStorage.muted === "true") {
      helpers.toggleMute();
    }
    document.querySelector("#mute").onclick = function() {
      return helpers.toggleMute();
    };
    return requestAnimationFrame(frame);
  };

  canvas.onmouseup = function(e) {
    var coords, i, j, len, ref, results;
    ref = screens[screen].items;
    results = [];
    for (j = 0, len = ref.length; j < len; j++) {
      i = ref[j];
      if (i.click) {
        coords = helpers.toCanvasTerms(i.x, i.y, i.image.height);
        if (helpers.getImageAlpha(i.image, e.clientX - coords.x, e.clientY - coords.y) > config.alphaThreshold) {
          results.push(i.click());
        } else {
          results.push(void 0);
        }
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  keysdown = [];

  downness = 0;

  window.onkeydown = function(e) {
    if (!keysdown[e.keyCode]) {
      keysdown[e.keyCode] = 2;
      if (e.keyCode === config.keys.down) {
        downness += 1;
        if (downness >= config.mindown) {
          return canvas.classList.add("flipped");
        }
      } else {
        return downness += downness > 0 ? -1 : 0;
      }
    }
  };

  window.onkeyup = function(e) {
    return keysdown[e.keyCode] = 0;
  };

  Item = (function() {
    function Item(x1, y1) {
      this.x = x1;
      this.y = y1;
      this.update = function() {};
      this.image = new Image;
      this.calcClickZone = function() {
        return {
          top: this.y + this.image.height,
          left: this.x,
          bottom: this.y,
          right: this.x + this.image.width
        };
      };
    }

    return Item;

  })();

  ImageItem = (function(superClass) {
    extend(ImageItem, superClass);

    function ImageItem(x, y, url, clickFunc) {
      if (clickFunc == null) {
        clickFunc = function() {};
      }
      ImageItem.__super__.constructor.call(this, x, y);
      this.image.src = url;
      this.click = clickFunc;
    }

    return ImageItem;

  })(Item);

  Screen = (function() {
    Screen.prototype.calcOrigin = function() {
      return 0;
    };

    function Screen(height, items, music, additional) {
      var i, o;
      if (additional == null) {
        additional = {};
      }
      this.height = height;
      this.items = items;
      this.music = new Audio;
      this.music.src = music;
      for (i in additional) {
        o = additional[i];
        this[i] = o;
      }
    }

    return Screen;

  })();

  screens[0] = new Screen(300, [
    new ImageItem(-227, 200, "img/logo-shaded.png", function() {
      screens[0].eggoCount++;
      if (screens[0].eggoCount === config.eggo) {
        return document.body.classList.add("eggomylego");
      }
    }), new ImageItem(-100, 130, "img/playbutton.png", function() {}), new ImageItem(-100, 30, "img/creditsbutton.png", function() {})
  ], "aud/carnivalloader.mp3", {
    eggoCount: 0
  });

}).call(this);
